allowBuilds:
  "@apollo/protobufjs": true
  "@datadog/pprof": true
  "@parcel/watcher": true
  "@reown/appkit": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  bufferutil: true
  esbuild: true
  keccak: true
  protobufjs: true
  utf-8-validate: true
overrides:
  date-fns: "4.3.0"
  vite: "8.0.14"
  rolldown: "1.0.2"
minimumReleaseAgeExclude:
  - '@hono/node-server@1.19.17'
  - '@powerhousedao/analytics-engine-browser@6.2.2-dev.20'
  - '@powerhousedao/analytics-engine-core@6.2.2-dev.20'
  - '@powerhousedao/analytics-engine-graphql@6.2.2-dev.20'
  - '@powerhousedao/analytics-engine-knex@6.2.2-dev.20'
  - '@powerhousedao/analytics-engine-pg@6.2.2-dev.20'
  - '@powerhousedao/builder-tools@6.2.2-dev.20'
  - '@powerhousedao/codegen@6.2.2-dev.20'
  - '@powerhousedao/common@6.2.2-dev.20'
  - '@powerhousedao/config@6.2.2-dev.20'
  - '@powerhousedao/connect@6.2.2-dev.20'
  - '@powerhousedao/design-system@6.2.2-dev.20'
  - '@powerhousedao/opentelemetry-instrumentation-reactor@6.2.2-dev.20'
  - '@powerhousedao/pglite-fs@6.2.2-dev.20'
  - '@powerhousedao/ph-cli@6.2.2-dev.20'
  - '@powerhousedao/powerhouse-vetra-packages@6.2.2-dev.20'
  - '@powerhousedao/reactor-api@6.2.2-dev.20'
  - '@powerhousedao/reactor-attachments@6.2.2-dev.20'
  - '@powerhousedao/reactor-browser@6.2.2-dev.20'
  - '@powerhousedao/reactor-drive@6.2.2-dev.20'
  - '@powerhousedao/reactor-mcp@6.2.2-dev.20'
  - '@powerhousedao/reactor@6.2.2-dev.20'
  - '@powerhousedao/shared@6.2.2-dev.20'
  - '@powerhousedao/switchboard@6.2.2-dev.20'
  - '@powerhousedao/vetra@6.2.2-dev.20'
  - '@renown/sdk@6.2.2-dev.20'
  - 'document-model@6.2.2-dev.20'
  - 'express-rate-limit@8.6.1'
  - 'viem@2.55.10'
