scalar Unknown
scalar DateTime
scalar Address
scalar AttachmentRef
scalar Amount_Tokens
scalar EthereumAddress
scalar EmailAddress
scalar Amount_Percentage
scalar Date
scalar URL
scalar Amount_Money
scalar OLabel
scalar Currency
scalar PHID
scalar OID
scalar Amount_Fiat
scalar Amount_Currency
scalar Amount_Crypto
scalar Amount
scalar Upload

type AppLicenseTypeState {
  app: PHID
  kind: String
  label: String
  validityDays: Int
  template: EnvironmentTemplate
  status: LicenseTypeStatus!
}

enum LicenseTypeStatus {
  DRAFT
  ACTIVE
  RETIRED
}

enum TemplateServiceType {
  CONNECT
  SWITCHBOARD
  CLINT
}

type EnvironmentTemplate {
  services: [TemplateService!]!
  packages: [TemplatePackage!]!
  size: String
  baseDomain: String
  packageRegistry: URL
}

type TemplateService {
  id: OID!
  type: TemplateServiceType!
  prefix: String
}

type TemplatePackage {
  id: OID!
  packageName: String
  version: String
}

# license_type

input SetLicenseTypeDetailsInput {
  app: PHID
  kind: String
  label: String
  validityDays: Int
}

input SetTemplateInput {
  size: String
  baseDomain: String
  packageRegistry: URL
}

input AddTemplateServiceInput {
  id: OID!
  type: TemplateServiceType!
  prefix: String
}

input AddTemplatePackageInput {
  id: OID!
  packageName: String
  version: String
}

input PublishLicenseTypeInput {
  _: Boolean
}

input RetireLicenseTypeInput {
  _: Boolean
}
