scalar Unknown
scalar DateTime
scalar Address
scalar AttachmentRef
scalar Amount_Tokens
scalar EthereumAddress
scalar EmailAddress
scalar Amount_Percentage
scalar Date
scalar URL
scalar Amount_Money
scalar OLabel
scalar Currency
scalar PHID
scalar OID
scalar Amount_Fiat
scalar Amount_Currency
scalar Amount_Crypto
scalar Amount
scalar Upload

type AppOwnerLicenseState {
  issuer: LicenseIssuerKind
  user: String
  app: PHID
  stage: PHID
  kind: String
  details: String
  issued: DateTime
  start: DateTime
  end: DateTime
  status: LicenseStatus!
  replacedBy: PHID
  revokedReason: String
}

enum LicenseIssuerKind {
  INVITE_CODE
  PUBLISHER_GRANT
  ACHRA_SUBSCRIPTION
}

enum LicenseStatus {
  ISSUED
  ACTIVE
  EXPIRED
  REVOKED
  REPLACED
}

# lifecycle

input IssueLicenseInput {
  app: PHID!
  user: String!
  issuer: LicenseIssuerKind!
  kind: String
  stage: PHID
  details: String
  issued: DateTime!
  start: DateTime!
  end: DateTime
  licenseType: PHID
  issuedBy: String
}

input ActivateLicenseInput {
  _: Boolean
}

input ExpireLicenseInput {
  _: Boolean
}

input RevokeLicenseInput {
  reason: String
}

input ReplaceLicenseInput {
  replacedBy: PHID!
}

input SetStageInput {
  stage: PHID
}

input MigrateLicenseInput {
  kind: String!
  user: String!
  details: String
}